CREATE TABLE IF NOT EXISTS post(
    id INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    title VARCHAR(255),
    categoryID INT NOT NULL,
    author VARCHAR(255),
    content LONGTEXT,
    PRIMARY KEY(id),
    CONSTRAINT FK_PostCategory FOREIGN KEY (categoryID)
    REFERENCES category(id)
)
